### ISSUE TITLE
Fails with Test-Alien-0.05 and Test-Alien-0.06

### ISSUE THREAD

**Issue by andk** [Perl5-Alien/Alien-Base-Extras#13]
As per subject. Sample fail reports:

0.05: http://www.cpantesters.org/cpan/report/68035910
0.06: http://www.cpantesters.org/cpan/report/68180725

Up-to-date table of pass/file and version of Test-Alien:

http://analysis.cpantesters.org/reports_by_field?distv=Acme-Alien-DontPanic-0.028;field=mod%3ATest%3A%3AAlien

HTH&&Thanks,

**Comment by plicease** [comment]
I believe this is already fixed in the repository, although thanks for the reminder, it looks like I wasn't requiring at least Test::Alien 0.05, which I should have been (fixed that too just now).  This should be fixed when the next version goes to CPAN.

**Comment by plicease** [comment]
I believe this to be now fixed on CPAN with the release of 0.029
